import type { Category, DashboardData, Project } from "./types";

// ⚠️ SERVER ONLY: 이 함수는 서버 컴포넌트에서만 호출됩니다.
// 실제 프로덕션에서는 DB 쿼리나 API 호출이 여기에 들어갑니다.
export async function fetchDashboardData(): Promise<DashboardData> {
  // 의도적 지연 - 서버 사이드 작업 시뮬레이션 (실제로는 DB/API 호출)
  await new Promise((resolve) => setTimeout(resolve, 100));

  const categories: Category[] = ["frontend", "backend", "mobile", "devops"];

  const projects: Project[] = [
    {
      id: "prj-001",
      name: "스마트시티 대시보드",
      description: "도시 센서 데이터를 실시간으로 시각화하는 운영 관제 화면",
      category: "frontend",
      status: "active",
      progress: 76,
      team: ["민준", "서연", "지후"],
      createdAt: "2026-01-08T09:00:00.000Z",
      stars: 842,
    },
    {
      id: "prj-002",
      name: "결제 시스템 마이그레이션",
      description: "레거시 정산 파이프라인을 이벤트 기반 구조로 전환",
      category: "backend",
      status: "active",
      progress: 63,
      team: ["도윤", "하린", "서준"],
      createdAt: "2025-11-21T09:00:00.000Z",
      stars: 711,
    },
    {
      id: "prj-003",
      name: "모바일 헬스케어",
      description: "웨어러블 수면 데이터를 분석해 개인화 리포트를 제공",
      category: "mobile",
      status: "active",
      progress: 51,
      team: ["지아", "유찬", "민서"],
      createdAt: "2026-02-03T09:00:00.000Z",
      stars: 506,
    },
    {
      id: "prj-004",
      name: "K8s 오토스케일러",
      description: "트래픽 예측 모델을 활용한 쿠버네티스 비용 최적화 도구",
      category: "devops",
      status: "completed",
      progress: 100,
      team: ["현우", "나은"],
      createdAt: "2025-09-14T09:00:00.000Z",
      stars: 934,
    },
    {
      id: "prj-005",
      name: "콘텐츠 편집 스튜디오",
      description: "마케팅 팀을 위한 블록 기반 랜딩 페이지 제작 환경",
      category: "frontend",
      status: "completed",
      progress: 100,
      team: ["서연", "태오", "라온"],
      createdAt: "2025-07-02T09:00:00.000Z",
      stars: 488,
    },
    {
      id: "prj-006",
      name: "로그 수집 게이트웨이",
      description: "분산 서비스의 로그를 표준 스키마로 정규화하는 백엔드 게이트웨이",
      category: "backend",
      status: "paused",
      progress: 38,
      team: ["시우", "하린"],
      createdAt: "2025-12-18T09:00:00.000Z",
      stars: 267,
    },
    {
      id: "prj-007",
      name: "현장 점검 앱",
      description: "오프라인 입력과 사진 증적 업로드를 지원하는 산업 현장 앱",
      category: "mobile",
      status: "active",
      progress: 82,
      team: ["유찬", "가온", "지아"],
      createdAt: "2025-10-29T09:00:00.000Z",
      stars: 612,
    },
    {
      id: "prj-008",
      name: "배포 안정성 레이더",
      description: "릴리스별 오류율과 롤백 지표를 한 화면에 집계",
      category: "devops",
      status: "active",
      progress: 69,
      team: ["현우", "도윤", "나은"],
      createdAt: "2026-03-10T09:00:00.000Z",
      stars: 755,
    },
    {
      id: "prj-009",
      name: "AI 상담 콘솔",
      description: "상담 이력과 추천 답변을 병렬로 탐색하는 상담원 워크벤치",
      category: "frontend",
      status: "active",
      progress: 44,
      team: ["민준", "라온", "민서"],
      createdAt: "2026-04-01T09:00:00.000Z",
      stars: 689,
    },
    {
      id: "prj-010",
      name: "권한 정책 엔진",
      description: "조직·역할·리소스 조건을 조합해 접근 결정을 수행",
      category: "backend",
      status: "completed",
      progress: 100,
      team: ["서준", "시우", "도윤"],
      createdAt: "2025-06-15T09:00:00.000Z",
      stars: 801,
    },
    {
      id: "prj-011",
      name: "주문 추적 모바일",
      description: "배송 상태와 기사 위치를 저전력 모드로 제공하는 고객 앱",
      category: "mobile",
      status: "paused",
      progress: 27,
      team: ["가온", "태오"],
      createdAt: "2026-01-27T09:00:00.000Z",
      stars: 143,
    },
    {
      id: "prj-012",
      name: "인프라 비용 분석기",
      description: "클라우드 비용 태그 누락과 과금 이상치를 탐지",
      category: "devops",
      status: "completed",
      progress: 100,
      team: ["나은", "현우", "하린"],
      createdAt: "2025-08-08T09:00:00.000Z",
      stars: 579,
    },
    {
      id: "prj-013",
      name: "데이터 품질 보드",
      description: "수집 테이블별 결측률과 지연 시간을 편집형 차트로 표시",
      category: "frontend",
      status: "active",
      progress: 58,
      team: ["서연", "지후", "라온"],
      createdAt: "2026-02-19T09:00:00.000Z",
      stars: 431,
    },
    {
      id: "prj-014",
      name: "알림 브로커 재설계",
      description: "푸시·메일·문자 발송을 우선순위 큐로 통합",
      category: "backend",
      status: "active",
      progress: 73,
      team: ["시우", "서준", "민서"],
      createdAt: "2025-12-02T09:00:00.000Z",
      stars: 390,
    },
    {
      id: "prj-015",
      name: "장애 훈련 런북",
      description: "서비스별 장애 시나리오와 복구 체크리스트를 자동 실행",
      category: "devops",
      status: "paused",
      progress: 35,
      team: ["태오", "현우"],
      createdAt: "2026-03-24T09:00:00.000Z",
      stars: 224,
    },
    {
      id: "prj-016",
      name: "매장 재고 스캐너",
      description: "바코드 인식과 재고 차감 플로우를 단순화한 태블릿 앱",
      category: "mobile",
      status: "completed",
      progress: 100,
      team: ["지아", "유찬", "민준"],
      createdAt: "2025-05-30T09:00:00.000Z",
      stars: 318,
    },
  ];

  const stats = {
    totalProjects: projects.length,
    activeProjects: projects.filter((project) => project.status === "active").length,
    completedProjects: projects.filter((project) => project.status === "completed").length,
    totalStars: projects.reduce((sum, project) => sum + project.stars, 0),
    totalTeamMembers: new Set(projects.flatMap((project) => project.team)).size,
  };

  return { projects, stats, categories };
}
